[symlinks.nvim]
target = "nvim"
name = "~/.config/nvim"

[symlinks.zsh]
target = "zsh"
name = "~/.config/zsh"

[symlinks.zshenv]
target = "zsh/.zshenv"
name = "~/.zshenv"

[symlinks.tmux]
target = "tmux/tmux.conf"
name = "~/.config/tmux/tmux.conf"

[symlinks.kitty]
target = "kitty"
name = "~/.config/kitty"

[symlinks.mise]
target = "mise"
name = "~/.config/mise"
