[simples.zsh]
cmd = "pacman -S --noconfirm zsh"
sudo = true
check = "which zsh"

[simples.zsh_default]
cmd = "chsh -s /usr/bin/zsh $USER"
sudo = true
check = "getent passwd $USER | grep -q zsh"
depends_on = ["zsh"]

[simples.neovim]
cmd = "pacman -S --noconfirm neovim"
sudo = true
check = "which nvim"

[simples.fzf]
cmd = "pacman -S --noconfirm fzf"
sudo = true
check = "which fzf"

[simples.curl]
cmd = "pacman -S --noconfirm curl"
sudo = true
check = "which curl"

[simples.mise]
cmd = "curl https://mise.run | sh"
sudo = false
check = "which mise"
depends_on = ["curl"]

[simples.zsh_autosuggestions]
cmd = "pacman -S --noconfirm zsh-autosuggestions"
sudo = true
check = "[ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]"

[simples.zsh_syntax_highlighting]
cmd = "pacman -S --noconfirm zsh-syntax-highlighting"
sudo = true
check = "[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]"

[simples.starship]
cmd = "pacman -S --noconfirm starship"
sudo = true
check = "which starship"

[simples.zoxide]
cmd = "pacman -S --noconfirm zoxide"
sudo = true
check = "which zoxide"

[simples.lsd]
cmd = "pacman -S --noconfirm lsd"
sudo = true
check = "which lsd"

[simples.mise_tools]
cmd = "mise install"
sudo = false
check = "mise list node | grep -q node && mise list rust | grep -q rust && mise list go | grep -q go && mise list uv | grep -q uv"
depends_on = ["mise"]
